site_name: Climate Tech Handbook
site_url: https://climate-tech-handbook-cms-fork.netlify.app
site_description: Your community source of truth for climate tech solutions.
use_directory_urls: True
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: green
  logo: assets/ct-handbook-logo-cropped.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    #   - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.instant
    - search.suggest
  icon:
    repo: fontawesome/brands/git-alt

repo_name: Contribute
repo_url: https://github.com/alexmayberry/climate-tech-handbook-test-deploy

extra_css:
  - stylesheets/extra.css

## NOTE: plugins need to be passed over to mkdocs.insiders.yml due to paid Insiders version of Material for MKDocs

plugins:
  - tags
  - search
  # - social
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: 🔗
      permalink_title: Link to this section of the page

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Additional plugins passed over to `mkdocs.insiders.yml` file

# === NAVIGATION ===

nav:
  - "Home": index.md
  - "Solutions":
      - solutions/index.md
      - Electricity: sector-electricity.md
      - Food, Agriculture, and Land Use: sector-food-agriculture-and-land-use.md
      - Industry: sector-industry.md
      - Transportation: sector-transportation.md
      - Buildings: sector-buildings.md
      - Land Sinks: sector-land-sinks.md
      - Coastal and Ocean Sinks: sector-coastal-and-ocean-sinks.md
      - Engineered Sinks: sector-engineered-sinks.md
      - Health and Education: sector-health-and-education.md
      - Climate Adaptation: sector-climate-adaptation.md
      - Research and Education: sector-research-and-education.md
      - Media and Journalism: sector-media-and-journalism.md
      - Advocacy or Policy: sector-advocacy-or-policy.md
      - Other: sector-other.md

  - "Resources":
      - resources/index.md
      - Career Guide: career-guide.md
      - Technologies: technologies.md
      - Full Glossary: glossary.md

  - "About":
      - About the Handbook: about/index.md
      #     - Frequently Asked Questions: faq.md
      - Contribute: contribute.md'

  - Blog: 
      - blog/index.md
